#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.States;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class FailedJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









            
            #line 9 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
  
    Layout = new LayoutPage(Strings.FailedJobsPage_Title);

    int from, perPage;
    string filterString = Query("filterString");
    string filterMethodString = Query("filterMethodString");
    string startDate = Query("startDate");
    string endDate = Query("endDate");
    string startTime = Query("startTime");
    string endTime = Query("endTime");

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    var monitor = Storage.GetMonitoringApi();

    var countParameters = new Dictionary<string, string>()
    {
        { "stateName", FailedState.StateName },
        { "filterString", filterString },
        { "filterMethodString", filterMethodString },
        { "startDate", startDate },
        { "endDate", endDate },
        { "startTime", startTime },
        { "endTime", endTime }
    };

    var jobCount = monitor.JobCountByStateName(countParameters);
    var pager = new Pager(from, perPage, jobCount)
    {
        JobsFilterText = filterString,
        JobsFilterMethodText = filterMethodString,
        JobsFilterStartDate = startDate,
        JobsFilterEndDate = endDate,
        JobsFilterStartTime = startTime,
        JobsFilterEndTime = endTime
    };

    var failedJobs = monitor.FailedJobs(pager);
    var servers = monitor.Servers();


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 53 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 56 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                           Write(Strings.FailedJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 58 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-success\">\r\n                ");


            
            #line 61 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
           Write(Strings.FailedJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 63 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                ");


            
            #line 67 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
           Write(Html.Raw(Strings.FailedJobsPage_FailedJobsNotExpire_Warning_Html));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");



WriteLiteral("            <div class=\"js-jobs-list\">\r\n                <div class=\"btn-toolbar b" +
"tn-toolbar-top\">\r\n");


            
            #line 71 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                     if (SpecificJobRequeue == true)
                    {

            
            #line default
            #line hidden
WriteLiteral(@"                        <div class=""btn-group"">
                            <button data-toggle=""dropdown"" data-target=""#advanced-requeue-dropdown""
                                    class=""js-jobs-list-select btn dropdown-toggle btn-sm btn-primary""
                                    aria-haspopup=""true"" aria-expanded=""false"" disabled=""disabled"">
                                <span class=""glyphicon glyphicon-repeat""></span>
                                ");


            
            #line 78 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                           Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </button>\r\n                            <ul class=\"d" +
"ropdown-menu\">\r\n                                <li>\r\n                          " +
"          <a class=\"js-jobs-list-command noselect\" data-url=\"");


            
            #line 82 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                  Write(Url.To("/jobs/failed/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        Default queue\r\n                      " +
"              </a>\r\n                                </li>\r\n                     " +
"           <li class=\"divider\" role=\"separator\"></li>\r\n");


            
            #line 87 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                 foreach (var server in servers)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li class=\"noselect dropdown-header\">");


            
            #line 89 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                     Write(server.Name.ToUpperInvariant().Split(':')[0]);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");


            
            #line 90 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                    foreach (var queue in server.Queues)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li>\r\n                                   " +
"         <a class=\"noselect js-jobs-list-command\"\r\n                             " +
"                  data-url=\"");


            
            #line 94 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                    Write(Url.To("/jobs/failed/specificrequeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                               id=\"");


            
            #line 95 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                              Write(queue);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                                ");


            
            #line 96 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                           Write(queue);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </a>\r\n                             " +
"           </li>\r\n");


            
            #line 99 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                    }
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </div>\r\n");


            
            #line 103 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button class=\"js-jobs-list-command btn btn-sm btn-primar" +
"y\"\r\n                                data-url=\"");


            
            #line 107 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     Write(Url.To("/jobs/failed/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                data-loading-text=\"");


            
            #line 108 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                              Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                disabled=\"disabled\">\r\n                        " +
"    <span class=\"glyphicon glyphicon-repeat\"></span>\r\n                          " +
"  ");


            
            #line 111 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                       Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </button>\r\n");


            
            #line 113 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <button class=\"js-jobs-list-command btn btn-sm btn-default\"\r\n" +
"                            data-url=\"");


            
            #line 115 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                 Write(Url.To("/jobs/failed/delete"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-loading-text=\"");


            
            #line 116 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                          Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-confirm=\"");


            
            #line 117 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     Write(Strings.Common_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <span class=\"glyphicon glyphicon-remove\"></span>\r\n   " +
"                     ");


            
            #line 119 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                   Write(Strings.Common_DeleteSelected);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </button>\r\n");


            
            #line 121 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                     if (EnableSearch == true)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button data-toggle=\"collapse\" data-target=\"#advanced-sea" +
"rch-bar\" class=\"btn btn-sm btn-success\">Advanced Search</button>\r\n");


            
            #line 124 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n\r\n");


            
            #line 127 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                 if (EnableSearch == true)
                {

            
            #line default
            #line hidden
WriteLiteral(@"                    <div id=""advanced-search-bar"" class=""collapse well"">
                        <h4 class=""advanced-search-header"">
                            Advanced Search
                        </h4>
                        <div class=""row"">
                            <div class=""col-md-12"">
                                <div class=""form-group"">
                                    <input type=""text"" value="""" id=""filterValueString"" class=""form-control"" placeholder=""Search..."" />
                                </div>
                                <div class=""form-group"">
");


            
            #line 139 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                      
                                        var currentDateTime = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
                                    

            
            #line default
            #line hidden
WriteLiteral(@"                                    <input id=""filterOnDateTime"" name=""filterOnDateTime"" type=""checkbox"" class=""js-jobs-filterOnDateTime-checked"" />
                                    <label for=""filterOnDateTime"">Filter on date time</label>

                                    <div id=""datetime-filters"" class=""row"">
                                        <div class=""col-xs-6"">
                                            <input type=""text"" value=""");


            
            #line 147 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                 Write(currentDateTime);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"datetimeselector-start form-control\" id=\"startDateTime\" />\r\n            " +
"                            </div>\r\n                                        <div" +
" class=\"col-xs-6\">\r\n                                            <input type=\"tex" +
"t\" value=\"");


            
            #line 150 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                 Write(currentDateTime);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""datetimeselector-end form-control"" id=""endDateTime"" />
                                        </div>
                                    </div>
                                </div>
                                <div class=""form-group"">
                                    <input id=""filterOnMethodName"" name=""filterOnMethodName"" type=""checkbox"" class=""js-jobs-filterOnMethodName-checked"" />
                                    <label for=""filterOnMethodName"">Filter on method name</label>
                                    <input type=""text"" value="""" id=""filterMethodString"" class=""form-control"" placeholder=""Method name..."" />
                                </div>
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-md-12"">
                                <button class=""js-jobs-filter-command btn btn-sm btn-success""
                                        data-url=""");


            
            #line 164 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                             Write(Url.To("/jobs/failed"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                                    <span class=""glyphicon glyphicon-repeat""></span>

                                    Filter jobs
                                </button>
                            </div>
                        </div>
                    </div>
");


            
            #line 172 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");


            
            #line 173 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
           Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                            <tr>
                                <th class=""min-width"">
                                    <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                                </th>
                                <th class=""min-width"">");


            
            #line 181 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                 Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 182 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                               Write(Strings.FailedJobsPage_Table_Failed);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 183 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                               Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            </tr>\r\n                        </thead>\r\n     " +
"                   <tbody>\r\n");


            
            #line 187 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                               var index = 0; 

            
            #line default
            #line hidden

            
            #line 188 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                             foreach (var job in failedJobs)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr class=\"js-jobs-list-row ");


            
            #line 190 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                        Write(!job.Value.InFailedState ? " obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 190 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                              Write(job.Value.InFailedState ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                    <td rowspan=\"");


            
            #line 191 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                             Write(job.Value.InFailedState ? " 2" : "1" );

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 192 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (job.Value.InFailedState)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input type=\"checkbox\" class=\"js-jobs" +
"-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 194 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                                 Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 195 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n                                    <t" +
"d class=\"min-width\" rowspan=\"");


            
            #line 197 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                               Write(job.Value.InFailedState ? " 2" : "1" );

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        ");


            
            #line 198 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                   Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 199 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (!job.Value.InFailedState)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <span title=\"");


            
            #line 201 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                    Write(Strings.Common_JobStateChanged_Text);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"glyphicon glyphicon-question-sign\"></span>\r\n");


            
            #line 202 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n                                    <t" +
"d class=\"min-width\">\r\n");


            
            #line 205 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (job.Value.FailedAt.HasValue)
                                        {
                                            if (RelativeTime == true)
                                            {
                                                
            
            #line default
            #line hidden
            
            #line 209 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                           Write(Html.RelativeTime(job.Value.FailedAt.Value));

            
            #line default
            #line hidden
            
            #line 209 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                            ;
                                            }
                                            else
                                            {
                                                
            
            #line default
            #line hidden
            
            #line 213 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                           Write(Html.Raw(job.Value.FailedAt.Value.ToString("dd/MM/yyyy HH:mm")));

            
            #line default
            #line hidden
            
            #line 213 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                                ;
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n                                    <t" +
"d>\r\n                                        <div>\r\n                             " +
"               ");


            
            #line 219 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                       Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n");


            
            #line 221 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (!String.IsNullOrEmpty(job.Value.ExceptionMessage))
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div style=\"color: #888;\">\r\n         " +
"                                       ");


            
            #line 224 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                           Write(job.Value.Reason);

            
            #line default
            #line hidden
WriteLiteral(" <a class=\"expander\" href=\"#\">");


            
            #line 224 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                           Write(index == 0 ? Strings.Common_LessDetails : Strings.Common_MoreDetails);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                            </div>\r\n");


            
            #line 226 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n                                </tr>\r" +
"\n");


            
            #line 229 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                if (job.Value.InFailedState)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\r\n                                       " +
" <td colspan=\"2\" class=\"failed-job-details\">\r\n                                  " +
"          <div class=\"expandable\" style=\"");


            
            #line 233 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                       Write(index++ == 0 ? " display: block;" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                                <h4>");


            
            #line 234 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                               Write(job.Value.ExceptionType);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                                                <p class=\"text-muted\">\r\n  " +
"                                                  ");


            
            #line 236 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                               Write(job.Value.ExceptionMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </p>\r\n\r\n");


            
            #line 239 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                 if (!String.IsNullOrEmpty(job.Value.ExceptionDetails))
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <pre class=\"stack-trace\"><cod" +
"e>");


            
            #line 241 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                              Write(Html.StackTrace(job.Value.ExceptionDetails));

            
            #line default
            #line hidden
WriteLiteral("</code></pre>\r\n");


            
            #line 242 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </div>\r\n                             " +
"           </td>\r\n                                    </tr>\r\n");


            
            #line 246 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n                ");


            
            #line 251 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
           Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 253 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
